[build]
  publish = "."

# Redirect para o CMS UI
[[redirects]]
  from = "/admin/config.yml"
  to   = "/admin/config.yml"
  status = 200

[[redirects]]
  from = "/admin"
  to   = "/admin/"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to   = "/admin/index.html"
  status = 200
  force = true 