[build]
  publish = "."

# Serve o config.yml do CMS diretamente
[[redirects]]
  from = "/admin/config.yml"
  to = "/admin/config.yml"
  status = 200
  force = true

# Redirect /admin para o index.html do CMS
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# Wildcard para servir o CMS SPA em rotas /admin/*
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200 