backend:
  name: git-gateway # Usa Netlify Identity para autenticação
  branch: main # Branch principal do seu repositório
  repo: thiagodelgado/curriculoclick # Repositório GitHub

locale: 'pt-BR' # Define o idioma da interface do CMS

media_folder: "dados/uploads" # Pasta onde as mídias serão salvas
public_folder: "/dados/uploads" # Caminho público para as mídias

# Adicionando as coleções de volta
collections:
  - name: "modelo" # Coleção para o arquivo único de modelo
    label: "Modelo Milena"
    files:
      - file: "dados/modelo.json"
        label: "Modelo Milena"
        name: "modelo"
        fields:
          - { label: "Nome completo",    name: "inicio.nome",           widget: "string" }
          - { label: "Profissão",         name: "inicio.profissao",      widget: "string" }
          - { label: "Foto de perfil",    name: "inicio.foto_perfil",    widget: "image" }
          - { label: "Idade",             name: "inicio.idade",          widget: "string" }
          - { label: "Estado civil",      name: "inicio.estado_civil",   widget: "string" }
          - { label: "Localização",       name: "inicio.localizacao",    widget: "string" }
          - { label: "Email",             name: "inicio.email",          widget: "string" }
          - { label: "Telefone",          name: "inicio.telefone",       widget: "string" }
          - { label: "Texto Botão Baixar",   name: "inicio.botao_baixar",   widget: "string" }
          - { label: "Facebook URL",      name: "social.facebook",       widget: "string" }
          - { label: "Instagram URL",     name: "social.instagram",      widget: "string" }
          - { label: "LinkedIn URL",      name: "social.linkedin",       widget: "string" }
          - { label: "Perfil profissional (Descrição)",name: "perfil.descricao",     widget: "text" }
          - label: "Habilidades"
            name: "habilidades"
            widget: "list"
            fields:
              - { label: "Nome",           name: "nome",                  widget: "string" }
              - { label: "Nível (0-100)",  name: "nivel",                 widget: "number", value_type: "int", min: 0, max: 100 }
          - label: "Idiomas"
            name: "idiomas"
            widget: "list"
            fields:
              - { label: "Nome",           name: "nome",                  widget: "string" }
              - { label: "Estrelas (1-5)", name: "estrelas",              widget: "number", value_type: "int", min: 1, max: 5 }
          - label: "Experiência Profissional"
            name: "experiencia_profissional"
            widget: "list"
            fields:
              - { label: "Cargo",          name: "cargo",                 widget: "string" }
              - { label: "Empresa",        name: "empresa",               widget: "string" }
              - { label: "Período",        name: "periodo",               widget: "string" }
              - { label: "Descrição",      name: "descricao",             widget: "text" }
          - label: "Certificações"
            name: "certificacoes"
            widget: "list"
            fields:
              - { label: "Título",         name: "titulo",                widget: "string" }
              - { label: "Ano",            name: "ano",                   widget: "string" }
              - { label: "Detalhes (Opcional)", name: "detalhes",              widget: "text", required: false }
          - label: "Educação"
            name: "educacao"
            widget: "list"
            fields:
              - { label: "Título",         name: "titulo",                widget: "string" }
              - { label: "Instituição",    name: "instituicao",           widget: "string" }
              - { label: "Período",        name: "periodo",               widget: "string" }
          - label: "Interesses"
            name: "interesses"
            widget: "list"
            max: 8 # Limita a seleção a no máximo 8 interesses
            field:
              label: "Interesse"
              name: "value"
              widget: "select"
              options:
                - { label: "🐶 Pets", value: "Pets" }
                - { label: "🌳 Natureza", value: "Natureza" }
                - { label: "✈️ Viagens", value: "Viagens" }
                - { label: "🎮 Vídeo Game", value: "Vídeo Game" }
                - { label: "🎬 Filmes/Séries", value: "Filmes/Séries" }
                - { label: "🍳 Culinária", value: "Culinária" }
                - { label: "🏅 Esportes", value: "Esportes" }
                - { label: "📚 Leitura", value: "Leitura" }
                - { label: "🎵 Música", value: "Música" }
                - { label: "📷 Fotografia", value: "Fotografia" }
                - { label: "🤝 Voluntariado", value: "Voluntariado" }
                - { label: "💻 Tecnologia", value: "Tecnologia" }
                - { label: "🌱 Jardinagem", value: "Jardinagem" }
                - { label: "🎨 Arte", value: "Arte" }
                - { label: "✍️ Escrita", value: "Escrita" }
                - { label: "💃 Dança", value: "Dança" }
                - { label: "🧘‍♂️ Meditação", value: "Meditação" }
                - { label: "👗 Moda", value: "Moda" }
                - { label: "📜 História", value: "História" }
                - { label: "🗣️ Idiomas", value: "Idiomas" }
                - { label: "🔭 Astronomia", value: "Astronomia" }
                - { label: "♟️ Xadrez", value: "Xadrez" }
                - { label: "🎙️ Podcasts", value: "Podcasts" }
                - { label: "🚴 Ciclismo", value: "Ciclismo" }
                - { label: "📦 Colecionismo", value: "Colecionismo" }
                - { label: "🔧 Customizável", value: "Customizavel" }
          - { label: "WhatsApp ativo?",    name: "whatsapp.ativo",        widget: "boolean", default: false }
          - { label: "WhatsApp número (completo com país/área)", name: "whatsapp.numero", widget: "string", required: false }
          - { label: "Cumprimento manhã",  name: "whatsapp.cumprimentos.manha", widget: "string", required: false }
          - { label: "Cumprimento tarde",  name: "whatsapp.cumprimentos.tarde", widget: "string", required: false }
          - { label: "Cumprimento noite",  name: "whatsapp.cumprimentos.noite", widget: "string", required: false }
          - { label: "Mensagem pós cumprimento", name: "whatsapp.mensagemPosCumprimento", widget: "string", required: false }

  - name: "curriculos" # Coleção para os múltiplos currículos
    label: "Currículos"
    folder: "dados" # Pasta onde os arquivos JSON estão
    preview_path: "/?id={{slug}}" # Caminho para visualizar o currículo no site final
    create: true # Permitir criar novos currículos
    slug: "{{slug}}" # Nome do arquivo será baseado no slug (geralmente do título/nome)
    extension: "json"
    pattern: '^((?!modelo).)*\.json$' # Padrão para encontrar arquivos .json exceto 'modelo.json'
    fields: # Os campos são os mesmos do modelo
      - { label: "Nome completo",    name: "inicio.nome",           widget: "string" }
      - { label: "Profissão",         name: "inicio.profissao",      widget: "string" }
      - { label: "Foto de perfil",    name: "inicio.foto_perfil",    widget: "image" }
      - { label: "Idade",             name: "inicio.idade",          widget: "string" }
      - { label: "Estado civil",      name: "inicio.estado_civil",   widget: "string" }
      - { label: "Localização",       name: "inicio.localizacao",    widget: "string" }
      - { label: "Email",             name: "inicio.email",          widget: "string" }
      - { label: "Telefone",          name: "inicio.telefone",       widget: "string" }
      - { label: "Texto Botão Baixar",   name: "inicio.botao_baixar",   widget: "string" }
      - { label: "Facebook URL",      name: "social.facebook",       widget: "string" }
      - { label: "Instagram URL",     name: "social.instagram",      widget: "string" }
      - { label: "LinkedIn URL",      name: "social.linkedin",       widget: "string" }
      - { label: "Perfil profissional (Descrição)",name: "perfil.descricao",     widget: "text" }
      - label: "Habilidades"
        name: "habilidades"
        widget: "list"
        fields:
          - { label: "Nome",           name: "nome",                  widget: "string" }
          - { label: "Nível (0-100)",  name: "nivel",                 widget: "number", value_type: "int", min: 0, max: 100 }
      - label: "Idiomas"
        name: "idiomas"
        widget: "list"
        fields:
          - { label: "Nome",           name: "nome",                  widget: "string" }
          - { label: "Estrelas (1-5)", name: "estrelas",              widget: "number", value_type: "int", min: 1, max: 5 }
      - label: "Experiência Profissional"
        name: "experiencia_profissional"
        widget: "list"
        fields:
          - { label: "Cargo",          name: "cargo",                 widget: "string" }
          - { label: "Empresa",        name: "empresa",               widget: "string" }
          - { label: "Período",        name: "periodo",               widget: "string" }
          - { label: "Descrição",      name: "descricao",             widget: "text" }
      - label: "Certificações"
        name: "certificacoes"
        widget: "list"
        fields:
          - { label: "Título",         name: "titulo",                widget: "string" }
          - { label: "Ano",            name: "ano",                   widget: "string" }
          - { label: "Detalhes (Opcional)", name: "detalhes",              widget: "text", required: false }
      - label: "Educação"
        name: "educacao"
        widget: "list"
        fields:
          - { label: "Título",         name: "titulo",                widget: "string" }
          - { label: "Instituição",    name: "instituicao",           widget: "string" }
          - { label: "Período",        name: "periodo",               widget: "string" }
      - label: "Interesses"
        name: "interesses"
        widget: "list"
        max: 8 # Limita a seleção a no máximo 8 interesses
        field:
          label: "Interesse"
          name: "value"
          widget: "select"
          options:
            - { label: "🐶 Pets", value: "Pets" }
            - { label: "🌳 Natureza", value: "Natureza" }
            - { label: "✈️ Viagens", value: "Viagens" }
            - { label: "🎮 Vídeo Game", value: "Vídeo Game" }
            - { label: "🎬 Filmes/Séries", value: "Filmes/Séries" }
            - { label: "🍳 Culinária", value: "Culinária" }
            - { label: "🏅 Esportes", value: "Esportes" }
            - { label: "📚 Leitura", value: "Leitura" }
            - { label: "🎵 Música", value: "Música" }
            - { label: "📷 Fotografia", value: "Fotografia" }
            - { label: "🤝 Voluntariado", value: "Voluntariado" }
            - { label: "💻 Tecnologia", value: "Tecnologia" }
            - { label: "🌱 Jardinagem", value: "Jardinagem" }
            - { label: "🎨 Arte", value: "Arte" }
            - { label: "✍️ Escrita", value: "Escrita" }
            - { label: "💃 Dança", value: "Dança" }
            - { label: "🧘‍♂️ Meditação", value: "Meditação" }
            - { label: "👗 Moda", value: "Moda" }
            - { label: "📜 História", value: "História" }
            - { label: "🗣️ Idiomas", value: "Idiomas" }
            - { label: "🔭 Astronomia", value: "Astronomia" }
            - { label: "♟️ Xadrez", value: "Xadrez" }
            - { label: "🎙️ Podcasts", value: "Podcasts" }
            - { label: "🚴 Ciclismo", value: "Ciclismo" }
            - { label: "📦 Colecionismo", value: "Colecionismo" }
            - { label: "🔧 Customizável", value: "Customizavel" }
      - { label: "WhatsApp ativo?",    name: "whatsapp.ativo",        widget: "boolean", default: false }
      - { label: "WhatsApp número (completo com país/área)", name: "whatsapp.numero", widget: "string", required: false }
      - { label: "Cumprimento manhã",  name: "whatsapp.cumprimentos.manha", widget: "string", required: false }
      - { label: "Cumprimento tarde",  name: "whatsapp.cumprimentos.tarde", widget: "string", required: false }
      - { label: "Cumprimento noite",  name: "whatsapp.cumprimentos.noite", widget: "string", required: false }
      - { label: "Mensagem pós cumprimento", name: "whatsapp.mensagemPosCumprimento", widget: "string", required: false } 